sonar.projectKey=Gingerminds-Symfony-Core
sonar.qualitygate.wait=true
sonar.sources=src,config,templates,assets
sonar.tests=tests
sonar.exclusions=vendor/**,var/**,assets/styles/_variables*.scss,src/Maker/skeleton/**
sonar.test.exclusions=tests/Application/var/**,tests/Application/assets/vendor/**
