<?php

declare(strict_types=1);

namespace Gingerminds\CoreBundle\Maker;

use Symfony\Bundle\MakerBundle\ConsoleStyle;
use Symfony\Bundle\MakerBundle\DependencyBuilder;
use Symfony\Bundle\MakerBundle\Generator;
use Symfony\Bundle\MakerBundle\InputConfiguration;
use Symfony\Bundle\TwigBundle\TwigBundle;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Yaml\Yaml;

/**
 * make:gm:crud-controller Namespace/Name (Laravel make:controller-full):
 * `App\Controller\Namespace\NameController` registered with
 * #[AsCrudController] (routes generated by the bundle), the admin templates
 * `templates/admin/<snake>/` and the `translations/admin.{fr,en}.yaml` keys.
 */
final class MakeCrudController extends AbstractResourceMaker
{
    public static function getCommandName(): string
    {
        return 'make:gm:crud-controller';
    }

    public static function getCommandDescription(): string
    {
        return 'Create a Gingerminds admin CRUD controller with its templates and translations';
    }

    public function configureCommand(Command $command, InputConfiguration $inputConfig): void
    {
        $this->addNameArgument($command);
    }

    public function configureDependencies(DependencyBuilder $dependencies, ?InputInterface $input = null): void
    {
        parent::configureDependencies($dependencies, $input);
        $dependencies->addClassDependency(TwigBundle::class, 'twig-bundle');
        $dependencies->addClassDependency(Yaml::class, 'yaml');
    }

    public function generate(InputInterface $input, ConsoleStyle $io, Generator $generator): void
    {
        $resource = $this->getResourceName($input, $generator);
        $this->resourceGenerator->generateCrudController($generator, $io, $resource);

        $this->finish($generator, $io, self::nextSteps($resource));
    }

    /**
     * @return list<string>
     */
    public static function nextSteps(ResourceName $resource): array
    {
        return [
            \sprintf(
                'The admin CRUD is served under <comment>/{admin_prefix}/%s</comment> (routes <comment>admin_%s_*</comment>, see <fg=yellow>bin/console debug:router</>).',
                str_replace('_', '-', $resource->snakePlural),
                $resource->snake,
            ),
            \sprintf(
                'It requires <comment>%s</comment>, <comment>%s</comment>, its repository and <comment>%s</comment> (make:gm:resource generates them all).',
                $resource->entityClass(),
                $resource->formClass(),
                $resource->voterClass(),
            ),
            \sprintf('Add columns/fields in <comment>templates/%s/</comment> and labels in <comment>translations/admin.*.yaml</comment>.', $resource->templateDirectory()),
        ];
    }
}
